import { SignInButton, useUser } from "@clerk/nextjs";
import { type NextPage } from "next";
import Head from "next/head";
import { type RouterOutputs, api } from "~/utils/api";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Image from "next/image";
import { LoadingPage } from "~/components/Loading";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
    const { user } = useUser();
    console.log(user);

    if (!user) return null;

    return (
        <div className="flex w-full gap-4">
            <Image src={user.profileImageUrl} alt="Profile image" className="h-14 w-14 rounded-full" width={56} height={56} />
            <input type="text" placeholder="Type some emojis!" className="grow bg-transparent" />
        </div>
    );
};

type PostWithUser = RouterOutputs["post"]["getAll"][number];
const PostView = (props: PostWithUser) => {
    const { post, author } = props;

    return (
        <div key={post.id} className="flex gap-3 border-b border-slate-400 p-4">
            <Image src={author.profilePicture} alt={`@${author.username}'s profile picture`} className="h-14 w-14 rounded-full" width={56} height={56} />
            <div className="flex flex-col">
                <div className="flex gap-1 font-bold text-slate-300">
                    <span>{`@${author.username}`}</span>
                    <span className="font-thin">・</span>
                    <span className="font-thin">{dayjs(post.createdAt).fromNow()}</span>
                </div>
                <span className="text-2xl">{post.content}</span>
            </div>
        </div>
    );
};

const Feed = () => {
    const { data, isLoading: postLoading } = api.post.getAll.useQuery();
    if (postLoading) return <LoadingPage />;
    if (!data) return <div>Something went wrong</div>;

    return (
        <div className="flex flex-col">
            {data?.map((fullPost) => (
                <PostView key={fullPost.post.id} {...fullPost} />
            ))}
        </div>
    );
};

const Home: NextPage = () => {
    const { isLoaded: userLoaded, isSignedIn } = useUser();

    // start fetching asap
    api.post.getAll.useQuery();

    // return empty div if user is not loaded
    if (!userLoaded) return <div />;

    return (
        <>
            <Head>
                <title>Create T3 App</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className="flex h-screen justify-center">
                <div className="h-full w-full border-x border-slate-400  md:max-w-2xl">
                    <div className="flex border-b border-slate-400 p-4">
                        {!isSignedIn && (
                            <div className="flex justify-center">
                                <SignInButton />
                            </div>
                        )}
                        {!!isSignedIn && <CreatePostWizard />}
                    </div>

                    <Feed />
                </div>
            </main>
        </>
    );
};

export default Home;
